version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "github-actions"
  directories:
    - "/"
    - "/scripts"
  schedule:
    interval: "monthly"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
