verbose: false
go:
  version: 1.24
  cgo: false
repository:
  path: github.com/maxwo/snmp_notifier
build:
  prefix: .
  flags: -a -tags netgo
  ldflags: |
    -s
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - description-template.tpl
    - LICENSE
    - NOTICE
crossbuild:
  platforms:
    # - darwin/386
    - darwin/amd64
    - dragonfly/amd64
    - freebsd/amd64
    - freebsd/386
    - freebsd/arm
    - linux/386
    - linux/amd64
    - linux/arm
    - linux/arm64
    - linux/mips64
    - linux/mips64le
    # - linux/ppc64
    - linux/ppc64le
    - linux/s390x
    - netbsd/amd64
    - netbsd/386
    - netbsd/arm
    - openbsd/amd64
    - openbsd/386
    - windows/amd64
    - windows/386
