serviceMonitor:
  enabled: true
  namespace: default
  labels:
    release: prometheus

image:
  tag: main

autoscaling:
  enabled: true

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: snmp-notifier.k8s.local
      paths:
        - path: /
          pathType: ImplementationSpecific

snmpNotifier:
  # extraArgs allows to pass SNMP notifier configurations, as described on https://github.com/maxwo/snmp_notifier#snmp-notifier-configuration
  extraArgs:
    - --alert.severity-label=severity

  # snmpDestinations is the list of SNMP servers to send the traps to
  snmpDestinations:
    - snmp-server:162

  # SNMP authentication secrets, that may be instanciated by the chart, or may use an already created secret
  snmpCommunity: public
  # snmpAuthenticationUsername: my_authentication_username
  # snmpAuthenticationPassword: my_authentication_password
  # snmpPrivatePassword: my_private_password
  # snmpCommunitySecret:
  #   name: test-secret
  #   key: communitySec
  snmpAuthenticationUsernameSecret:
    name: test-secret
    key: authenticationUsernameSec
  snmpAuthenticationPasswordSecret:
    name: test-secret
    key: authenticationPasswordSec
  snmpPrivatePasswordSecret:
    name: test-secret
    key: privatePasswordSec

  # trapTemplates allows to customize the description of the traps, and add traps' user objects
  trapTemplates:
    description: |
      {{- if .Alerts -}}
      {{ len .Alerts }}/{{ len .DeclaredAlerts }} alerts are firing:

      {{ range $severity, $alerts := (groupAlertsByLabel .Alerts "severity") -}}
      Status: {{ $severity }}

      {{- range $index, $alert := $alerts }}
      - Alert: {{ $alert.Labels.alertname }}
        Summary: {{ $alert.Annotations.summary }}
        Description: {{ $alert.Annotations.description }}
      {{ end }}
      {{ end }}
      {{ else -}}
      Status: OK
      {{- end -}}

    userObjects:
      - subOid: 1
        template: |
          {{- if .Alerts -}}
          Status: NOK
          {{- else -}}
          Status: OK
          {{- end -}}
      - subOid: 5
        template: |
          This is a constant
