apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  communitySec: Y29tbXVuaXR5X2Zyb21fc2VjcmV0Cg==
  authenticationUsernameSec: YXV0aGVudGljYXRpb25Vc2VybmFtZV9mcm9tX3NlY3JldAo=
  authenticationPasswordSec: YXV0aGVudGljYXRpb25QYXNzd29yZF9mcm9tX3NlY3JldAo=
  privatePasswordSec: cHJpdmF0ZVBhc3N3b3JkX2Zyb21fc2VjcmV0Cg==
